/**
 * SchemaModel -> DBML (https://dbml.dbdiagram.io/docs/) text.
 *
 * The generated .dbml is a portable snapshot of the ERD that can be pasted
 * directly into https://dbdiagram.io for visual editing/sharing, independent
 * of the Postgres DDL / Liam viewer paths.
 */

import type { SchemaModel } from "./model.js";

const CANONICAL_TO_DBML: Record<string, string> = {
  string: "varchar",
  text: "text",
  integer: "integer",
  decimal: "decimal",
  boolean: "boolean",
  date: "date",
  datetime: "timestamp",
  json: "json",
};

function dbmlType(canonicalType: string, maxLength: number | undefined, enumRef: string | undefined): string {
  if (enumRef) return enumRef;
  const base = CANONICAL_TO_DBML[canonicalType] ?? "varchar";
  if (base === "varchar" && maxLength) return `varchar(${maxLength})`;
  return base;
}

function quoteNote(note: string): string {
  return `'${note.replace(/'/g, "\\'")}'`;
}

export function toDbml(schema: SchemaModel): string {
  const out: string[] = [];

  if (schema.name) {
    out.push(`// ${schema.name}${schema.version ? ` (v${schema.version})` : ""}`);
    out.push(`// Generated by @dlo/erd from an EML (.eml.mmd) document.`);
    out.push("");
  }

  for (const en of schema.enums) {
    out.push(`Enum ${en.name} {`);
    for (const v of en.values) out.push(`  ${v}`);
    out.push(`}`);
    out.push("");
  }

  for (const entity of schema.entities) {
    out.push(`Table ${entity.tableName} {`);
    for (const field of entity.fields) {
      const type = dbmlType(field.canonicalType, field.maxLength, field.enumRef);
      const settings: string[] = [];
      if (field.isPrimaryKey) settings.push("pk");
      if (field.isUnique && !field.isPrimaryKey) settings.push("unique");
      if (!field.isOptional && !field.isPrimaryKey) settings.push("not null");
      if (field.comment) settings.push(`note: ${quoteNote(field.comment)}`);
      const settingsStr = settings.length ? ` [${settings.join(", ")}]` : "";
      out.push(`  ${field.name} ${type}${settingsStr}`);
    }
    if (entity.indexes.length > 0) {
      out.push("");
      out.push("  indexes {");
      for (const idx of entity.indexes) {
        const cols = idx.columns.length > 1 ? `(${idx.columns.join(", ")})` : idx.columns[0]!;
        out.push(`    ${cols}${idx.unique ? " [unique]" : ""}`);
      }
      out.push("  }");
    }
    if (entity.comment) {
      out.push("");
      out.push(`  Note: ${quoteNote(entity.comment)}`);
    }
    out.push(`}`);
    out.push("");
  }

  for (const entity of schema.entities) {
    for (const fk of entity.foreignKeys) {
      const target = schema.entities.find((e) => e.name === fk.targetEntity);
      if (!target) continue;
      // Many-to-one FK: `>` reads "many refs one" (the FK-holding side is many).
      out.push(
        `Ref: ${entity.tableName}.${fk.field} > ${target.tableName}.${fk.targetField}` +
          (fk.relationshipLabel ? ` // ${fk.relationshipLabel}` : ""),
      );
    }
  }

  return out.join("\n").replace(/\n{3,}/g, "\n\n").trim() + "\n";
}
