// relay.config.js — relay-compiler input (Architecture.md "Plumbing & Conventions" folder
// layout; Implementation.md m17). `schema.graphql` is generated by `npm run schema:emit`
// (scripts/emit-schema.ts) from src/graphql/schema.root.graphql plus every src/modules/**/*.graphql
// fragment — it is never hand-edited and never committed. `export default`, not
// `module.exports`: package.json declares `"type": "module"`, so every `.js` file in this project
// (this one included) is loaded as ESM.
export default {
  src: "./src",
  schema: "./schema.graphql",
  language: "typescript",
  artifactDirectory: "./src/__generated__",
  exclude: ["**/node_modules/**", "**/__generated__/**", "**/__mocks__/**"],
};
